### ISSUE TITLE
Redeploying the container on Portainer deletes accounts 

### ISSUE THREAD

**Issue by IlanKD** [alexbates/Tamari#7]
Hi ! Me again,

I think editing the container on portainer (thus re deploying it) deletes every account. I can't connect after editing/updating the container but I can register again. When I log back in after registering, my preferences are gone

**Comment by IlanKD** [comment]
ok I think it's a me issue again because my volume isn't properly mounted somehow..
![image](https://github.com/user-attachments/assets/4e4ee21e-6f43-4676-a252-d3a24f4cbb70)
![image](https://github.com/user-attachments/assets/7d5334f2-415a-4617-bce4-0fc7092cb84e)

**Comment by alexbates** [comment]
Hi! That does sound like it is not using a volume for persistent storage. I have no experience with Portainer, but I think I will try it out this weekend to see how to properly configure it. I need to add that to the Documentation!

**Comment by felixdollack** [comment]
@IlanKD I am running Tamari with portioner on a RaspberryPi.
I updated the deployment multiple times and both my account as well as my recipes were restored etch time.

I paste my config below if it helps:

```
version: "3"
services:
    pairdrop:
        image: "alexbates/tamari:1.1"
        container_name: tamari
        restart: unless-stopped
        ports:
            - "4888:4888"
        volumes:
            - tamari-recipe-data:/app/appdata

volumes:
  tamari-recipe-data:
    name: tamari-appdata
```
