### ISSUE TITLE
CSS and Scripts are being blocked by HTTPS (HTTP) in application with Traefik reverse proxy

### ISSUE THREAD

**Issue by vanvonlj** [alexbates/Tamari#9]
**Description:**

I'm experiencing an issue where both CSS and JavaScript files over HTTP, but the browser is blocking them due to the `https` scheme. I've set up a reverse proxy using Traefik, which is supposed to handle HTTPS traffic, and Convert HTTP to HTTPS.

Here's what happens:

* When accessing the site via HTTP (e.g., in Chrome), all CSS and JavaScript files are served correctly.
* However, when accessing the site via HTTPS (e.g., in Firefox), the browser blocks the access due to the `https` scheme.

**Comment by alexbates** [comment]
Hi, I just got a chance to try out Traefik for testing. I was initially experiencing the same issue as you. Here is a sample Traefik config that resolves the issue:

```yaml
http:
  routers:
    tamari-http:
      entryPoints:
        - web
      rule: "Host(`tamari.example.com`)"
      middlewares:
        - redirect-to-https

    tamari-https:
      entryPoints:
        - websecure
      rule: "Host(`tamari.example.com`)"
      service: tamari-service
      tls: {}
      middlewares:
        - security-headers
        - fix-host
        - limit-body-size

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    security-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-For: "{client.ip}"
          X-Real-IP: "{client.ip}"
          X-Forwarded-Proto: "https"
          Host: "{host}"
        customResponseHeaders:
          Content-Security-Policy: "upgrade-insecure-requests"

    fix-host:
      headers:
        customRequestHeaders:
          Host: "tamari.example.com"

    limit-body-size:
      buffering:
        maxRequestBodyBytes: 400000000  # 400MB

  services:
    tamari-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:4888"
        passHostHeader: true

tls:
  certificates:
    - certFile: "/etc/ssl/certs/tamari.example.com/fullchain.pem"
      keyFile: "/etc/ssl/certs/tamari.example.com/privkey.pem"
```

I just added the sample config to the documentation as well. In the future I will see if there is a way to have Tamari detect HTTPS automatically, and avoid the need for these custom headers in the Traefik config. Let me know if any issues!
